services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PGPORT}:5432"
    volumes:
      - sgca_pgdata:/var/lib/postgresql/data
      - ./SGCA_DB/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: sgca_backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  sgca_pgdata: